# Generated by Django 3.1.1 on 2020-09-22 08:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('hostname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('auto_update', models.BooleanField(default=False)),
                ('production_step', models.CharField(choices=[('Mid-assembly QC', 'Assembly Qc'), ('Curing', 'Curing'), ('Cutting', 'Cutting'), ('Deathrig testing', 'Deathrig'), ('Dry assembly', 'Dry Assembly'), ('End-of-line QC', 'Eol Qc'), ('Goods-In QC', 'Goods In Qc'), ('Heater assembly', 'Heater Assembly'), ('Hot tightening', 'Hot Tightening'), ('Inspection', 'Inspection'), ('Packing', 'Packing'), ('Potting', 'Potting'), ('Pressing', 'Pressing'), ('Unique ID setting', 'Uid Setting')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sku_trained', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueID',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, validators=[core.models.validate_work_order_code])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_test_data', models.BooleanField(default=False)),
            ],
        ),
    ]
