# Generated by Django 3.1.1 on 2020-11-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_zeroinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='production_step',
            field=models.CharField(choices=[('Mid-assembly QC', 'Assembly Qc'), ('Curing', 'Curing'), ('Cutting', 'Cutting'), ('Deathrig testing', 'Deathrig'), ('Dry assembly', 'Dry Assembly'), ('End-of-line QC', 'Eol Qc'), ('Goods-In QC', 'Goods In Qc'), ('Greasing', 'Greasing'), ('Heater assembly', 'Heater Assembly'), ('Hot tightening', 'Hot Tightening'), ('Inspection', 'Inspection'), ('Packing', 'Packing'), ('Potting', 'Potting'), ('Pressing', 'Pressing'), ('Unique ID setting', 'Uid Setting')], max_length=255),
        ),
    ]
