# Generated by Django 3.1.1 on 2022-01-17 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_operator_sku_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueid',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
