# Generated by Django 3.1.1 on 2022-01-17 12:25

from django.db import migrations

from core.uid_schemas import UID_SCHEMAS


def set_uid_schemas(apps, schema_editor):
    """
    Set the schemas on all existing UIDs, where possible.
    Due to the existence of older test data, some of them will fail. Since this is just a migration,
    leave those IDs untouched for the time being, rather than deleting them.
    """
    UniqueID = apps.get_model("core", "UniqueID")
    db_alias = schema_editor.connection.alias

    all_uids = UniqueID.objects.using(db_alias).all()
    for uid in all_uids:
        # Customised model methods aren't available in migrations, so we'll need to manually
        # replicate the schema matching that's normally implemented on the model.
        schemas = UID_SCHEMAS.match_all(uid.code)
        uid.matches_schemas = [s.name for s in schemas]
        uid.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_uniqueid_matches_schemas'),
    ]

    operations = [
        migrations.RunPython(set_uid_schemas, migrations.RunPython.noop, elidable=True)
    ]
