# Generated by Django 3.2.12 on 2022-09-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_machineusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineusage',
            options={'ordering': ['-logged_in_at']},
        ),
    ]
