# Generated by Django 3.2.12 on 2022-09-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_machineusage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['code']},
        ),
    ]
