# Generated by Django 3.2.12 on 2022-09-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sku_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['name']},
        ),
    ]
