# Generated by Django 3.2.12 on 2023-04-08 15:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220920_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueid',
            name='matches_schemas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('V6_BARCODE', 'V6 Barcode'), ('V7_SERIAL', 'V7 Serial Number'), ('HEMERA_QR', 'Hemera QR Code'), ('ROTO_QR', 'Revo Roto QR Code')], max_length=255), default=list, size=None),
        ),
    ]
