# Generated by Django 3.1.1 on 2021-04-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v7_post_curing_qc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='current_open_circuit_threshold',
            field=models.FloatField(default=0.015),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='current_short_circuit_threshold',
            field=models.FloatField(default=0.225),
        ),
    ]
