# Generated by Django 3.1.1 on 2021-07-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v7_post_curing_qc', '0004_remove_temperature_mosfet_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v7curingqcevent',
            name='result',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Cancelled', 'Cancelled'), ('Disconnected', 'Disconnected'), ('Temperature sensor open circuit', 'Temp Sensor Open Circuit'), ('Temperature sensor short circuit', 'Temp Sensor Short Circuit'), ('Current sensor open circuit', 'Current Sensor Open Circuit'), ('Current sensor short circuit', 'Current Sensor Short Circuit'), ('Current too low', 'Current Too Low'), ('Current too high', 'Current Too High'), ('Heating rate too slow', 'Heating Too Slow'), ('Heating rate too fast', 'Heating Too Fast'), ('Heating timeout', 'Heating Timeout'), ('Cooling timeout', 'Cooling Timeout'), ('Overheat', 'Overheat'), ('Thermal runaway', 'Thermal Runaway'), ('Heater/sensor leakage', 'Heater Sensor Leakage'), ('Sensor/mandrel leakage', 'Sensor Mandrel Leakage'), ('Heater/mandrel leakage', 'Heater Mandrel Leakage')], default='Passed', max_length=255),
        ),
    ]
