# Generated by Django 3.1.1 on 2021-08-23 15:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v7_post_curing_qc', '0005_add_hipot_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='v7curingqcevent',
            name='log_temperatures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='V7CuringQCLogEntry',
        ),
    ]
