# Generated by Django 3.1.1 on 2021-08-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v7_post_curing_qc', '0006_auto_20210823_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='v7curingqcevent',
            name='tested_circuit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='v7curingqcevent',
            name='tested_leakage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='v7curingqcevent',
            name='tested_thermal_cycling',
            field=models.BooleanField(default=False),
        ),
    ]
