# Generated by Django 3.1.1 on 2021-09-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v7_post_curing_qc', '0007_add_test_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='v7curingqcconfig',
            name='thermistor_type',
            field=models.CharField(choices=[('Thermistor', 'Thermistor'), ('PT100', 'Pt100'), ('PT1000', 'Pt1000'), ('BCN Thermistor', 'Bcn Thermistor')], default='Thermistor', max_length=255),
        ),
    ]
