# Generated by Django 3.1.1 on 2021-10-27 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v7_post_curing_qc', '0008_v7curingqcconfig_thermistor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='cooling_timeout',
            field=models.FloatField(default=180.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='current_max',
            field=models.FloatField(default=4.7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='current_min',
            field=models.FloatField(default=0.001, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='current_open_circuit_threshold',
            field=models.FloatField(default=0.015, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='current_short_circuit_threshold',
            field=models.FloatField(default=0.225, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='current_test_pwm',
            field=models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='heatup_timeout',
            field=models.FloatField(default=180.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='mosfet_max_current_after_disable',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='overheat_temp',
            field=models.FloatField(default=300.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='safe_handling_temperature',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='temperature_open_circuit_threshold',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='temperature_short_circuit_threshold',
            field=models.FloatField(default=350.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='thermal_max_hot_temp',
            field=models.FloatField(default=270.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='thermal_min_hot_temp',
            field=models.FloatField(default=220.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='thermal_target_temp',
            field=models.FloatField(default=250.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='thermistor_type',
            field=models.CharField(choices=[('Thermistor', 'Thermistor'), ('PT100', 'Pt100'), ('PT1000', 'Pt1000'), ('BCN Thermistor', 'Bcn Thermistor')], max_length=255),
        ),
    ]
