# Generated by Django 3.1.1 on 2021-12-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v7_post_curing_qc', '0008_v7curingqcconfig_thermistor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='v7curingqcevent',
            name='successful_thermal_cycles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
