# Generated by Django 3.1.1 on 2022-01-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v7_post_curing_qc', '0009_v7curingqcevent_successful_thermal_cycles'),
        ('v7_post_curing_qc', '0009_add_configuration_validators'),
    ]

    operations = [
    ]
