# Generated by Django 3.1.1 on 2022-01-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v7_post_curing_qc', '0010_merge_20220106_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v7curingqcconfig',
            name='thermistor_type',
            field=models.CharField(choices=[('Thermistor', 'Thermistor'), ('104NT-4 Thermistor', 'Thermistor 104Nt4'), ('PT100', 'Pt100'), ('PT1000', 'Pt1000'), ('BCN Thermistor', 'Bcn Thermistor')], max_length=255),
        ),
    ]
