# Generated by Django 3.1.1 on 2022-01-19 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v7_post_curing_qc', '0011_add_104nt4_thermistor'),
    ]

    operations = [
        migrations.AddField(
            model_name='v7curingqcconfig',
            name='wattage',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
