# Generated by Django 3.2.12 on 2022-03-08 11:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v7_post_curing_qc', '0013_add_thermistor_type_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v7curingqcevent',
            name='log_temperatures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None, verbose_name='Temperatures (°C)'),
        ),
    ]
