# Generated by Django 3.2.12 on 2023-04-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('completed', models.BooleanField()),
                ('tested_leakage', models.BooleanField()),
                ('tested_circuit', models.BooleanField()),
                ('tested_thermal_cycling', models.BooleanField()),
                ('successful_thermal_cycles', models.BooleanField()),
            ],
        ),
    ]
