# Generated by Django 3.1.1 on 2020-11-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_models', '0002_add_grease_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='HemeraGreaseConfig',
            fields=[
                ('configuration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_models.configuration')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('base_models.configuration',),
        ),
        migrations.CreateModel(
            name='HemeraGreaseEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_models.event')),
                ('fail_state', models.CharField(choices=[('None', 'None'), ('Motor stalled', 'Motor Stall'), ('Dispenser E Stop triggered', 'E Stop'), ('Hemera removed prematurely', 'Removal')], default='None', max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('base_models.event',),
        ),
    ]
