# Generated by Django 3.1.1 on 2020-12-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hemeragreaseevent',
            name='fail_state',
            field=models.CharField(choices=[('None', 'None'), ('Motor stalled', 'Motor Stall'), ('Dispenser E Stop triggered', 'E Stop'), ('Hemera removed prematurely', 'Removal'), ('Duet had an error', 'Duet Error')], default='None', max_length=255),
        ),
    ]
