# Generated by Django 3.2.12 on 2022-09-07 11:22

from django.db import migrations
from django.db.transaction import atomic
from django_bulk_update.helper import bulk_update

from core.utils import suppress_autotime


@atomic
def forwards(apps, schema_editor):
    HemeraEvent = apps.get_model('hemera', 'HemeraGreaseEvent')
    Event = apps.get_model('base_models', 'Event')

    with suppress_autotime(Event, ['date_updated']):
        sub_events = HemeraEvent.objects.only('id', 'fail_state')
        events = Event.objects.filter(id__in=sub_events).only('fail_state_tmp')
        for obj, sub_obj in zip(events, sub_events):
            obj.fail_state_tmp = sub_obj.fail_state
        bulk_update(events, update_fields=['fail_state_tmp'], batch_size=10000)


class Migration(migrations.Migration):

    dependencies = [
        ('hemera', '0002_add_duet_error_failure'),
        ('base_models', '0009_event_fail_state')
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='hemeragreaseevent',
            name='fail_state',
        ),
    ]
