# Generated by Django 3.1.1 on 2021-01-12 07:53

from django.db import migrations, models

import base_models.non_polymorphic_cascade


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_operator_sku_trained'),
        ('base_models', '0002_add_grease_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anyitem',
            name='sku',
            field=models.ForeignKey(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, related_name='items', to='core.sku'),
        ),
        migrations.AlterField(
            model_name='bulkitem',
            name='work_order',
            field=models.ForeignKey(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, related_name='bulk_items', to='core.workorder'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sku',
            field=models.ForeignKey(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, related_name='configurations', to='core.sku'),
        ),
        migrations.AlterField(
            model_name='event',
            name='item',
            field=models.ForeignKey(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, to='base_models.anyitem'),
        ),
        migrations.AlterField(
            model_name='event',
            name='machine',
            field=models.ForeignKey(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, to='core.machine'),
        ),
        migrations.AlterField(
            model_name='event',
            name='operator',
            field=models.ForeignKey(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, to='core.operator'),
        ),
        migrations.AlterField(
            model_name='event',
            name='work_order',
            field=models.ForeignKey(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, to='core.workorder'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='event',
            field=models.ForeignKey(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, related_name='logs', to='base_models.event'),
        ),
        migrations.AlterField(
            model_name='singleitem',
            name='uid',
            field=models.OneToOneField(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, related_name='item', to='core.uniqueid'),
        ),
    ]
