# Generated by Django 3.1.1 on 2021-01-20 03:50

from django.db import migrations, models

import base_models.non_polymorphic_cascade


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_operator_sku_trained'),
        ('base_models', '0003_add_ih_press'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='item',
            field=models.ForeignKey(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, related_name='events', to='base_models.anyitem'),
        ),
        migrations.AlterField(
            model_name='event',
            name='machine',
            field=models.ForeignKey(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, related_name='events', to='core.machine'),
        ),
        migrations.AlterField(
            model_name='event',
            name='operator',
            field=models.ForeignKey(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, related_name='events', to='core.operator'),
        ),
        migrations.AlterField(
            model_name='event',
            name='work_order',
            field=models.ForeignKey(on_delete=base_models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, related_name='events', to='core.workorder'),
        ),
    ]
