# Generated by Django 3.1.1 on 2022-02-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_models', '0006_delete_logentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='production_step_field',
            field=models.CharField(choices=[('Mid-assembly QC', 'Assembly Qc'), ('Curing', 'Curing'), ('Cutting', 'Cutting'), ('Dry assembly', 'Dry Assembly'), ('End-of-line QC', 'Eol Qc'), ('Goods-In QC', 'Goods In Qc'), ('Greasing', 'Greasing'), ('Heater assembly', 'Heater Assembly'), ('Hot tightening', 'Hot Tightening'), ('Inspection', 'Inspection'), ('Packing', 'Packing'), ('Potting', 'Potting'), ('Pressing', 'Pressing'), ('Unique ID setting', 'Uid Setting')], editable=False, max_length=255),
        ),
    ]
