# Generated by Django 3.2.12 on 2022-03-08 11:10

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_models', '0007_remove_deathrig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='log_timepoints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]), default=list, size=None, verbose_name='Timepoints (s)'),
        ),
    ]
