# Generated by Django 3.2.12 on 2022-09-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_models', '0008_alter_event_log_timepoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fail_state_tmp',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
