# Generated by Django 3.2.12 on 2022-09-07 12:04

from django.db import migrations
from django.db.transaction import atomic
from django_bulk_update.helper import bulk_update

from core.utils import suppress_autotime


@atomic
def forwards(apps, schema_editor):
    Event = apps.get_model('base_models', 'Event')

    # this is to update existing Events based on their respective save methods
    with suppress_autotime(Event, ['date_updated']):
        events = Event.objects.only('fail_state', 'failed')
        for obj in events:
            if obj.failed is True:
                if obj.fail_state == "None":
                    obj.fail_state = "Unknown"
        bulk_update(events, update_fields=['fail_state'], batch_size=10000)


class Migration(migrations.Migration):

    dependencies = [
        ('base_models', '0009_event_fail_state'),
        ('generic', '0002_remove_genericevent_fail_state'),
        # ('prusa_nube_press', '0006_remove_nubepressevent_fail_state'),
        ('v7_post_curing_qc', '0015_remove_v7curingqcevent_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='fail_state_tmp',
            new_name='fail_state',
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
