# Generated by Django 3.2.12 on 2022-09-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_models', '0010_rename_fail_state_tmp_event_fail_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'ordering': ['sku']},
        ),
    ]
